name: Docker Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker build -t serf-bot-image .
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker tag serf-bot-image boogiedk/serf-bot-image:latest
        docker push boogiedk/serf-bot-image:latest
